server:
  port: 8085
spring:
  application:
    name: task-assigned
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-18-224-140-254.us-east-2.compute.amazonaws.com:8761/eureka
